### PR TITLE
Fix: issue related to token validity

### PR DESCRIPTION
**Pull request by premagarwals**

### CODE REVIEW

**Review by rohan-b-84 — COMMENTED** [review]
Sahi lag raha hai, isko frontend pe bhi handle karo, tab merge karte hai

**Comment by Dami-18** [comment]
> Sahi lag raha hai, isko frontend pe bhi handle karo, tab merge karte hai

Kya handle karna hai frontend pe?

**Comment by Dami-18** [comment]
Till then @rohan-b-84 please merge pr for loader and regex removal (as mentioned by @proffapt ). Without loader, app looks glitchy

**Comment by premagarwals** [comment]
> Sahi lag raha hai, isko frontend pe bhi handle karo, tab merge karte hai

I think wo toast me chala jayega na error, Jiske liye koi specific change ki jarurat nahi frontend me iirc.

**Review by proffapt — COMMENTED** [review]
Can we do it like, when this error is received, the frontend triggers logout itself?

cc: @rohan-b-84

**Comment by proffapt** [comment]
@Dami-18 ^^

**Comment by Dami-18** [comment]
> @Dami-18 ^^

Ha abhi wahi dekh rahi

**Comment by rohan-b-84** [comment]
> when this error is received, the frontend triggers logout itself

This is what I meant

**Review by rohan-b-84 — APPROVED** [review]
LGTM

**Pull request merged**
